# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(409, 236)
        self.L_text1 = QtWidgets.QLabel(Form)
        self.L_text1.setGeometry(QtCore.QRect(120, 90, 271, 16))
        self.L_text1.setObjectName("L_text1")
        self.L_image = QtWidgets.QLabel(Form)
        self.L_image.setGeometry(QtCore.QRect(20, 50, 91, 91))
        self.L_image.setText("")
        self.L_image.setObjectName("L_image")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(160, 170, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.OK_clicked)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.L_text1.setText(_translate("Form", "Please upload the reference image first"))
        self.pushButton.setText(_translate("Form", "OK"))

