# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Error(object):
    def setupUi(self, Error):
        Error.setObjectName("Error")
        Error.resize(512, 236)
        self.L_text1 = QtWidgets.QLabel(Error)
        self.L_text1.setGeometry(QtCore.QRect(130, 90, 361, 16))
        self.L_text1.setObjectName("L_text1")
        self.L_image = QtWidgets.QLabel(Error)
        self.L_image.setGeometry(QtCore.QRect(20, 50, 91, 91))
        self.L_image.setText("")
        self.L_image.setObjectName("L_image")
        self.pushButton = QtWidgets.QPushButton(Error)
        self.pushButton.setGeometry(QtCore.QRect(210, 160, 81, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Error)
        self.pushButton.clicked.connect(Error.OK_clicked)
        QtCore.QMetaObject.connectSlotsByName(Error)

    def retranslateUi(self, Error):
        _translate = QtCore.QCoreApplication.translate
        Error.setWindowTitle(_translate("Error", "Error"))
        self.L_text1.setText(_translate("Error", "Please upload the reference image first"))
        self.pushButton.setText(_translate("Error", "OK"))
