# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interaction.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1564, 555)
        self.B_sharpening = QtWidgets.QPushButton(Form)
        self.B_sharpening.setGeometry(QtCore.QRect(860, 40, 131, 41))
        self.B_sharpening.setObjectName("B_sharpening")
        self.F_ShowBefore = QtWidgets.QFrame(Form)
        self.F_ShowBefore.setGeometry(QtCore.QRect(20, 30, 791, 481))
        self.F_ShowBefore.setFrameShape(QtWidgets.QFrame.Box)
        self.F_ShowBefore.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F_ShowBefore.setObjectName("F_ShowBefore")
        self.L_note1 = QtWidgets.QLabel(self.F_ShowBefore)
        self.L_note1.setGeometry(QtCore.QRect(10, 0, 641, 61))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.L_note1.setFont(font)
        self.L_note1.setObjectName("L_note1")
        self.B_select = QtWidgets.QPushButton(self.F_ShowBefore)
        self.B_select.setGeometry(QtCore.QRect(640, 10, 121, 41))
        self.B_select.setObjectName("B_select")
        self.L_ShowPic = QtWidgets.QLabel(self.F_ShowBefore)
        self.L_ShowPic.setGeometry(QtCore.QRect(30, 60, 311, 311))
        self.L_ShowPic.setText("")
        self.L_ShowPic.setObjectName("L_ShowPic")
        self.F_ShowAfter = QtWidgets.QFrame(Form)
        self.F_ShowAfter.setGeometry(QtCore.QRect(1020, 30, 511, 481))
        self.F_ShowAfter.setFrameShape(QtWidgets.QFrame.Box)
        self.F_ShowAfter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F_ShowAfter.setObjectName("F_ShowAfter")
        self.label = QtWidgets.QLabel(self.F_ShowAfter)
        self.label.setGeometry(QtCore.QRect(20, 10, 351, 51))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.L_ShowAfter = QtWidgets.QLabel(self.F_ShowAfter)
        self.L_ShowAfter.setGeometry(QtCore.QRect(30, 60, 311, 311))
        self.L_ShowAfter.setText("")
        self.L_ShowAfter.setObjectName("L_ShowAfter")
        self.F_ShowAfter.raise_()
        self.F_ShowBefore.raise_()
        self.B_sharpening.raise_()

        self.retranslateUi(Form)
        self.B_select.clicked.connect(Form.getImage_click)
        self.B_sharpening.clicked.connect(Form.sharpening_click)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.B_sharpening.setText(_translate("Form", "Highlight"))
        self.L_note1.setText(_translate("Form", "please choose the image that need to be processed:"))
        self.B_select.setText(_translate("Form", "Select"))
        self.label.setText(_translate("Form", "The image after sharpening:"))
