# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lighting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1564, 592)
        self.F_ShowBefore = QtWidgets.QFrame(Form)
        self.F_ShowBefore.setGeometry(QtCore.QRect(20, 30, 791, 481))
        self.F_ShowBefore.setFrameShape(QtWidgets.QFrame.Box)
        self.F_ShowBefore.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F_ShowBefore.setObjectName("F_ShowBefore")
        self.L_note1 = QtWidgets.QLabel(self.F_ShowBefore)
        self.L_note1.setGeometry(QtCore.QRect(10, 0, 641, 61))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.L_note1.setFont(font)
        self.L_note1.setObjectName("L_note1")
        self.B_select = QtWidgets.QPushButton(self.F_ShowBefore)
        self.B_select.setGeometry(QtCore.QRect(90, 50, 201, 41))
        self.B_select.setObjectName("B_select")
        self.L_ShowPic = QtWidgets.QLabel(self.F_ShowBefore)
        self.L_ShowPic.setGeometry(QtCore.QRect(50, 130, 311, 311))
        self.L_ShowPic.setText("")
        self.L_ShowPic.setObjectName("L_ShowPic")
        self.L_ShowPic_2 = QtWidgets.QLabel(self.F_ShowBefore)
        self.L_ShowPic_2.setGeometry(QtCore.QRect(440, 130, 311, 311))
        self.L_ShowPic_2.setText("")
        self.L_ShowPic_2.setObjectName("L_ShowPic_2")
        self.B_select_2 = QtWidgets.QPushButton(self.F_ShowBefore)
        self.B_select_2.setGeometry(QtCore.QRect(480, 50, 201, 41))
        self.B_select_2.setObjectName("B_select_2")
        self.F_ShowAfter = QtWidgets.QFrame(Form)
        self.F_ShowAfter.setGeometry(QtCore.QRect(1020, 30, 511, 481))
        self.F_ShowAfter.setFrameShape(QtWidgets.QFrame.Box)
        self.F_ShowAfter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F_ShowAfter.setObjectName("F_ShowAfter")
        self.label = QtWidgets.QLabel(self.F_ShowAfter)
        self.label.setGeometry(QtCore.QRect(20, 10, 351, 51))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.L_ShowAfter = QtWidgets.QLabel(self.F_ShowAfter)
        self.L_ShowAfter.setGeometry(QtCore.QRect(70, 80, 311, 311))
        self.L_ShowAfter.setText("")
        self.L_ShowAfter.setObjectName("L_ShowAfter")
        self.B_lighting = QtWidgets.QPushButton(Form)
        self.B_lighting.setGeometry(QtCore.QRect(850, 60, 131, 41))
        self.B_lighting.setObjectName("B_lighting")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(1230, 530, 301, 41))
        self.pushButton.setObjectName("pushButton")
        self.F_ShowAfter.raise_()
        self.F_ShowBefore.raise_()
        self.B_lighting.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Form)
        self.B_select.clicked.connect(Form.getImage_click)
        self.B_lighting.clicked.connect(Form.lighting_click)
        self.B_select_2.clicked.connect(Form.getImage2_click)
        self.pushButton.clicked.connect(Form.returnHP_click)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.L_note1.setText(_translate("Form", "please choose the image that need to be processed:"))
        self.B_select.setText(_translate("Form", "Select Target image"))
        self.B_select_2.setText(_translate("Form", "Select Source image"))
        self.label.setText(_translate("Form", "The image after relighting:"))
        self.B_lighting.setText(_translate("Form", "Lighting"))
        self.pushButton.setText(_translate("Form", "Back to home page"))
